# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RollbarClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RollbarClient
  pod 'Alamofire', '~> 4.4'
  pod 'KeychainAccess'
  pod 'PMAlertController'
  pod 'SwiftyJSON'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'JNDropDownMenu'
  
  target 'RollbarClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
